# Configuration for Codecov
#
# Kona's code coverage is available at
# https://app.codecov.io/gh/op-rs/kona
#
# Reference: https://docs.codecov.com/docs/codecovyml-reference

coverage:
  range: 80..100
  round: down
  precision: 1
  status:
    project:
      default:
        threshold: 1%
      # Unit tests should have higher coverage requirements
      unit:
        threshold: 1%
      # E2E tests may have lower coverage due to integration complexity
      e2e:
        threshold: 1%
      # Proof/action tests may have variable coverage
      proof:
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto
        only_pulls: true
      # Unit tests should maintain higher patch coverage
      unit:
        target: auto
        threshold: 1%
        base: auto
        only_pulls: true
      # E2E tests can have more lenient patch requirements
      e2e:
        target: auto
        threshold: 1%
        base: auto
        only_pulls: true
      # Proof tests can have lenient patch requirements
      proof:
        target: auto
        threshold: 1%
        base: auto
        only_pulls: true

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  require_changes: true
  hide_project_coverage: false

ignore:
  - "examples/**/*"
  - "**/test_util*"
  # Ignore noop files
  - "**/noop.rs"


flag_management:
  individual_flags:
    - name: unit
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - name: e2e
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - name: proof
      statuses:
        - type: project
          target: auto
          threshold: 1%

fixes:
  - "/home/runner/work/kona/kona/::"