# Configuration for Codecov
#
# Kona's code coverage is available at
# https://app.codecov.io/gh/op-rs/kona
#
# Reference: https://docs.codecov.com/docs/codecovyml-reference

coverage:
  range: 90..100
  round: down
  precision: 1
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto
        only_pulls: true

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  require_changes: true
  hide_project_coverage: false

ignore:
  - "examples/**/*"
  - "**/test_util*"
  # Ignore providers
  - "crates/providers"
  # Ignore noop files
  - "**/noop.rs"
  # Node - WIP
  - "bin/node"
  - "crates/node/engine"
  - "crates/node/service"
