[workspace]
members = []

[package]
name = "maili-rpc"
version = "0.2.9"
description = "RPC for Optimism"
edition = "2021"
license = "MIT"
rust-version = "1.82"
authors = ["clabby", "refcell"]
homepage = "https://github.com/op-rs/kona"
repository = "https://github.com/op-rs/kona"
keywords = ["ethereum", "optimism", "crypto"]
categories = ["cryptography", "cryptography::cryptocurrencies"]
exclude = ["**/target"]

[dependencies]
kona-rpc = "0.1.0"

[features]
default = []
serde = ["kona-rpc/serde"]
std = ["kona-rpc/std"]
