# Config example at: https://lychee.cli.rs/usage/config/

verbose = "debug"

no_progress = false

exclude_all_private = false

exclude = [
    'foo.bar',
    'localhost'
]

# Files or directories to exclude
exclude_path = [
    './CHANGELOG.md',
    '**/CHANGELOG.md'
]