# Config example at: https://lychee.cli.rs/usage/config/

verbose = "debug"

no_progress = false

exclude_all_private = false

# Accept status codes - 403 is often returned by private repos instead of 404
accept = [200, 403]

exclude = [
    'foo.bar',
    'localhost',
    '^https://github\.com/op-rs/kona/pull/',
    '^https://www\.intel\.com/content/www/us/en/developer/tools/trust-domain-extensions/documentation\.html',
    'https://sepolia-optimism\.etherscan\.io'
]

# exclude_path values are ignored if cli <inputs> is glob pattern that matches
# this list, at least in lycheeverse/lychee-action@v2