# Config example at: https://lychee.cli.rs/usage/config/

verbose = "debug"

no_progress = false

exclude_all_private = false

# Files or directories to exclude
exclude_path = [
    "./CHANGELOG.md"
]

# Files to scan
files = [
    "**/*.md",
    "**/*.mdx",
    "**/*.html"
]