# Config example at: https://lychee.cli.rs/usage/config/

verbose = "debug"

no_progress = false

exclude_all_private = false

exclude = [
    'foo.bar',
    'localhost',
    '^https://github\.com/op-rs/kona/pull/'
]