[workspace]
members = []

[package]
name = "maili-protocol"
version = "0.2.9"
description = "Protocol types for the OP Stack"
edition = "2021"
license = "MIT"
rust-version = "1.85"
authors = ["clabby", "refcell"]
homepage = "https://github.com/op-rs/kona"
repository = "https://github.com/op-rs/kona"
keywords = ["ethereum", "optimism", "crypto"]
categories = ["cryptography", "cryptography::cryptocurrencies"]
exclude = ["**/target"]

[dependencies]
kona-protocol = "0.1.0"

[features]
default = []
std = ["kona-protocol/std"]
