[package]
name = "maili-registry"
version = "0.2.8"
description = "Registry for Optimism"
edition = "2021"
license = "MIT"
rust-version = "1.81"
authors = ["clabby", "refcell"]
homepage = "https://github.com/op-rs/kona"
repository = "https://github.com/op-rs/kona"
keywords = ["ethereum", "optimism", "crypto"]
categories = ["cryptography", "cryptography::cryptocurrencies"]
exclude = ["**/target"]

[dependencies]
kona-registry = "0.1.0"

[features]
default = []
std = ["kona-registry/std"]
