# Use the shared network across all stacks
networks:
  stf-net:
    external: true

services:
  prometheus:
    restart: unless-stopped
    image: prom/prometheus:latest
    volumes:
      - "prometheus_data:/prometheus"
      - "./prometheus:/etc/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    networks:
      - stf-net

  grafana:
    restart: unless-stopped
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      PROMETHEUS_URL: ${PROMETHEUS_URL:-http://prometheus:9090}
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./grafana/datasources:/etc/grafana/provisioning/datasources"
      - "./grafana/dashboards:/etc/grafana/provisioning_temp/dashboards"
    entrypoint: >
      sh -c "cp -r /etc/grafana/provisioning_temp/dashboards/. /etc/grafana/provisioning/dashboards &&
        find /etc/grafana/provisioning/dashboards/ -name '*.json' -exec sed -i 's/$${DS_PROMETHEUS}/Prometheus/g' {} \+ &&
        /run.sh"
    networks:
      - stf-net

  op-rs-op-sepolia-reth:
    container_name: reth
    build:
      context: .
      dockerfile: op-reth/op-reth.dockerfile
    ports:
      - "9430:9430" # metrics
      - "30333:30333/tcp" # eth/66 peering
      - "30333:30333/udp" # eth/66 peering
      - "8200:8200" # rpc
      - "8201:8201" # engine
    volumes:
      - "./datadirs/reth-2:/db"
    networks:
      - stf-net

  op-rs-op-sepolia-kona-node:
    container_name: kona
    depends_on:
      - prometheus
      - op-rs-op-sepolia-reth
    env_file:
      - path: default.env
      - path: publicnode.env
      - path: override.env
        required: false
    build:
      context: .
      dockerfile: kona-node/kona-node.dockerfile
    ports:
      - "9223:9223/tcp" # p2p
      - "9223:9223/udp" # p2p
      - "9431:9431" # metrics
      - "5060:5060" # rpc
    volumes:
      - "./datadirs/kona-node:/db"
    networks:
      - stf-net



volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  #  reth_data:
  #    driver: local
  #  kona_data:
  #    driver: local
  logs:
    driver: local




