# print actions
default:
	@just -l

# initialize project
init: && build-kona-node (create-docker-network "stf-net") up
	git submodule update --init --recursive
	./generate-jwt.sh

checkout branch:
	#!/bin/bash
	(cd kona-node/kona && git fetch origin && git checkout "{{branch}}")

reset-git:
	#!/bin/bash
	(cd kona-node/kona && (git pull origin "$(git branch --show-current)" || true) && git reset --hard "origin/$(git branch --show-current)")

# build kona
build-kona-node:
	#!/bin/bash
	(cd kona-node/kona && cargo build --bin kona-node --release)

reset-and-build: reset-git build-kona-node


generate-jwt:
  @echo "Attempting to generate JWT secret"
  @bash ./generate-jwt.sh


# run node (show logs)
# Spins up the docker environment
up DETACH="": generate-jwt
	docker compose up {{ DETACH }}

# run node (no logs)
# Spins up the docker environment
upd: (up "--detach")

# Winds down the docker containers gracefully
down: #rmi
	docker compose down

# remove images to force rebuild
rmi:
	docker image ls "*-op-rs-op-sepolia-*" --format="{{ "{{" }}.Repository{{ "}}" }}" | xargs -r docker rmi

# Restarts the environment
restart: down up

restart-with-main: down (checkout "main") (reset-and-build) up

create-docker-network NETWORK="stf-net":
	-docker network create {{NETWORK}}

setup-ubuntu:
	-which apt && sudo apt install just git rustup make clang tmux vim
	-rustup install nightly

start: stop up

stop: down rmi
