[package]
name = "kona-node"
version = "0.1.0"
description = "Kona Consensus Node"

edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
# workspace
kona-cli.workspace = true
kona-p2p.workspace = true
kona-engine.workspace = true
kona-genesis.workspace = true
kona-registry = { workspace = true, features = ["tabled"] }
kona-node-service.workspace = true
kona-rpc = { workspace = true, features = ["std"] }

# alloy
alloy-primitives.workspace = true
alloy-rpc-types-engine = { workspace = true, features = ["jwt", "serde"] }

# op-alloy
op-alloy-provider.workspace = true

# tui
ratatui.workspace = true
color-eyre.workspace = true
crossterm = { workspace = true, features = ["event-stream"] }

# general
dirs.workspace = true
url.workspace = true
tokio-stream.workspace = true
tracing-appender.workspace = true
discv5.workspace = true
tabled.workspace = true
libp2p.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde_json = { workspace = true, features = ["std"] }
jsonrpsee = { workspace = true, features = ["server"] }
clap = { workspace = true, features = ["derive", "env"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
