[package]
name = "kona-node"
version = "0.1.0"
description = "Kona Consensus Node"

edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
# workspace
kona-cli.workspace = true
kona-node-service.workspace = true
kona-p2p.workspace = true
kona-genesis.workspace = true
kona-registry.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-rpc-types-engine = { workspace = true, features = ["jwt", "serde"] }

# general
url.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde_json = { workspace = true, features = ["std"] }
clap = { workspace = true, features = ["derive", "env"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
