[workspace]
members = []

[package]
name = "maili-serde"
version = "0.2.9"
description = "Serde related helpers for Maili"
edition = "2021"
license = "MIT"
rust-version = "1.82"
authors = ["clabby", "refcell"]
homepage = "https://github.com/op-rs/kona"
repository = "https://github.com/op-rs/kona"
keywords = ["ethereum", "optimism", "crypto"]
categories = ["cryptography", "cryptography::cryptocurrencies"]
exclude = ["**/target"]

[dependencies]
kona-serde = "0.1.0"

[features]
default = []
std = ["kona-serde/std"]
