[package]
name = "kona-node-service"
description = "An implementation of the OP Stack consensus node service"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
kona-p2p.workspace = true
kona-engine.workspace = true
kona-genesis.workspace = true
kona-derive.workspace = true
kona-protocol.workspace = true
kona-providers-alloy.workspace = true
kona-rpc.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-rpc-types-engine = { workspace = true, features = ["jwt", "serde"] }
alloy-provider.workspace = true
alloy-eips.workspace = true
alloy-transport.workspace = true

# op-alloy
op-alloy-network.workspace = true
op-alloy-rpc-types-engine = { workspace = true, features = ["std"] }

# general
libp2p.workspace = true
url.workspace = true
thiserror.workspace = true
async-trait.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tokio-util.workspace = true
futures.workspace = true
libp2p-identity = { workspace = true, features = ["secp256k1"] }
