[package]
name = "kona-rpc"
version = "0.2.0"
description = "Optimism RPC Types and API"

edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
authors.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
kona-protocol = {workspace = true, features = ["serde", "std"]}
kona-p2p.workspace = true
kona-engine.workspace = true
kona-macros.workspace = true
kona-genesis = {workspace = true, features = ["serde", "std"]}
kona-supervisor-rpc = { workspace = true, features = ["client"] }

# `interop` feature
kona-interop = { workspace = true, features = ["serde"] }

# OP Alloy
op-alloy-consensus.workspace = true
op-alloy-rpc-types-engine = {workspace = true, features = ["serde", "std"]}
op-alloy-rpc-types.workspace = true

# Alloy
alloy-eips = { workspace = true, features = ["serde", "std"] }
alloy-rpc-types-engine = { workspace = true, features = ["serde", "std"] }
alloy-primitives = { workspace = true, features = ["map", "rlp", "serde", "std"] }

# Misc
libp2p.workspace = true
tracing.workspace = true
thiserror.workspace = true
derive_more = { workspace = true, default-features = false, features = [
    "display",
    "from",
    "constructor",
    "std",
] }
async-trait.workspace = true
tokio = { workspace = true, features = ["time"] }
ipnet = { workspace = true }

# `serde`
serde = { workspace = true, features = ["std"] }

# `jsonrpsee`
jsonrpsee = { workspace = true, features = ["macros", "server"] }
getrandom = { workspace = true, features = ["wasm_js"] } # req for wasm32-unknown-unknown
op-alloy-rpc-jsonrpsee.workspace = true

# `reqwest` feature
alloy-rpc-client = { workspace = true, features = ["reqwest"], optional = true }

# `metrics` feature
metrics = { workspace = true, optional = true }

[dev-dependencies]
serde_json.workspace = true

[features]
default = []
reqwest = ["client", "dep:alloy-rpc-client"]
client = [
    "jsonrpsee/client",
    "jsonrpsee/async-client",
    "op-alloy-rpc-types/jsonrpsee",
    "op-alloy-rpc-jsonrpsee/client",
]
metrics = ["dep:metrics"]
