name: Action Tests
on:
  push:
    branches: [main]
  merge_group:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  action-tests:
    name: FPP actions (${{ matrix.kind }})
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        kind: ["single", "interop"]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
          toolchain: 1.85
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Prep action test environment
        run: just monorepo
      - name: Restore cached Forge artifacts
        id: cache-forge-build-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            monorepo/packages/contracts-bedrock/forge-artifacts
            monorepo/packages/contracts-bedrock/artifacts
            monorepo/packages/contracts-bedrock/cache
          key: ${{ matrix.kind }}-forge-artifacts
      - name: Setup Go toolchain
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.7"
          cache-dependency-path: |
            monorepo/go.sum
      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v2.0.0
        with:
          gotestsum_version: 1.12.1
      - name: Setup yq
        uses: dcarbone/install-yq-action@v1
      - name: Extract monorepo forge version
        id: collect-versions
        run: |
          append_v() {
            local input="$1"

            if [[ "$input" == v* ]] || [[ "$input" == nightly* ]]; then
              echo "$input"
            else
              echo "v$input"
            fi
          }
          forge_version=$(append_v "$(yq '.tools.forge' monorepo/mise.toml | tr -d '\n')")
          echo "forge-version=$forge_version" >> $GITHUB_OUTPUT
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ steps.collect-versions.outputs.forge-version }}
      - name: Run Action Tests (${{ matrix.kind }})
        run: |
          source <(cargo llvm-cov show-env --export-prefix)
          just "action-tests-${{ matrix.kind }}"
          cargo llvm-cov report --lcov --output-path actions_cov.lcov
      - name: Cache forge artifacts
        id: cache-forge-build-save
        uses: actions/cache/save@v4
        with:
          path: |
            monorepo/packages/contracts-bedrock/forge-artifacts
            monorepo/packages/contracts-bedrock/artifacts
            monorepo/packages/contracts-bedrock/cache
          key: ${{ matrix.kind }}-forge-artifacts
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,RUST
          files: actions_cov.lcov
