name: Client + Host
on:
  push:
    branches: [main]
  merge_group:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  host-client-offline-runs:
    name: ${{ matrix.target}} | ${{ matrix.name }}
    strategy:
      matrix:
        target: ["native", "asterisc"]
        name: ["OP Sepolia (Holocene) - Block #26215604"]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
          toolchain: 1.85
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          prefix-key: ${{ matrix.target }}-${{ matrix.name }}
      - name: Log into ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone `asterisc` repository
        if: "!contains(matrix.target, 'native')"
        run: |
          git clone https://github.com/ethereum-optimism/asterisc.git
      - name: Setup Go toolchain
        if: "!contains(matrix.target, 'native')"
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.6"
          cache-dependency-path: |
            asterisc/go.sum
      - name: Build `asterisc`
        if: "!contains(matrix.target, 'native')"
        run: |
          cd asterisc && git checkout v1.3.0 && make build-rvgo
          mv ./rvgo/bin/asterisc /usr/local/bin/
      - name: Set run environment
        run: |
          if [[ ${{ contains(matrix.name, 26215604) }} == true ]]; then
            BLOCK_NUMBER=26215604
            echo "BLOCK_NUMBER=$BLOCK_NUMBER" >> $GITHUB_ENV
            echo "L2_CLAIM=0x7415d942f80a34f77d344e4bccb7050f14e593f5ea33669d27ea01dce273d72d" >> $GITHUB_ENV
            echo "L2_OUTPUT_ROOT=0xaa34b62993bd888d7a2ad8541935374e39948576fce12aa8179a0aa5b5bc787b" >> $GITHUB_ENV
            echo "L2_HEAD=0xf4adf5790bad1ffc9eee315dc163df9102473c5726a2743da27a8a10dc16b473" >> $GITHUB_ENV
            echo "L1_HEAD=0x010cfdb22eaa13e8cdfbf66403f8de2a026475e96a6635d53c31f853a0e3ae25" >> $GITHUB_ENV
            echo "L2_CHAIN_ID=11155420" >> $GITHUB_ENV
            echo "WITNESS_TAR_NAME=holocene-op-sepolia-$BLOCK_NUMBER-witness.tar.zst" >> $GITHUB_ENV
          fi
      - name: Decompress witness data directory
        run: |
          tar --zstd -xvf ./bin/client/testdata/$WITNESS_TAR_NAME -C .
      - name: Run host + client offline
        working-directory: ./bin/client
        run: |
          source <(cargo llvm-cov show-env --export-prefix)

          mkdir -p ../../target
          just run-client-${{ matrix.target }}-offline \
            $BLOCK_NUMBER \
            $L2_CLAIM \
            $L2_OUTPUT_ROOT \
            $L2_HEAD \
            $L1_HEAD \
            $L2_CHAIN_ID

          cargo llvm-cov report --lcov --output-path client_host_cov.lcov
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,RUST
          files: client_host_cov.lcov
