name: Deny

on:
  push:
    branches: [main]
  pull_request:
  schedule: [cron: "00 00 * * *"]

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: EmbarkStudios/cargo-deny-action@v2
