name: Documentation Deployment

# This Github action is adapted from reth.
# Reference: https://github.com/paradigmxyz/reth/blob/main/.github/workflows/book.yml

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, closed]
  merge_group:

jobs:
  build-docs-vocs:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "24.4.0"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.1
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install Playwright browsers
        # Required for rehype-mermaid to render Mermaid diagrams during build
        run: |
          cd docs/
          bun i
          npx playwright install --with-deps chromium

      - name: Build Vocs
        run: |
          cd docs/ && bun run build
          echo "Vocs Build Complete"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs/docs/dist"

  deploy-docs-vocs:
    # Only deploy if a push to main
    if: github.ref_name == 'main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [build-docs-vocs]

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    timeout-minutes: 60

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
