name: Kurtosis E2E Tests
on:
  push:
    branches: [main]
  merge_group:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  node-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    name: ${{ matrix.devnet-config }}-tests
    strategy:
      matrix:
        devnet-config: ["simple-kona", "simple-kona-geth", "large-kona"]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false
      - uses: taiki-e/install-action@just
      - name: Setup Go 1.24.3
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.24.3'
      - uses: jdx/mise-action@v2       # installs Mise + runs `mise install`
      - name: test with ${{ matrix.devnet-config }} devnet
        run: just build-devnet-and-test-e2e "${{ matrix.devnet-config }}" node
