name: Kurtosis E2E Tests
on:
  push:
    branches: [main]
  merge_group:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  kurtosis-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    name: test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85
      - uses: jdx/mise-action@v2       # installs Mise + runs `mise install`
        with:
          cache: true                  # enable built‑in tool cache
      - name: test with simple-kona devnet
        run: cd tests && just test-e2e simple-kona ${{ github.event.pull_request.head.sha }}
  