name: Publish Prestate Artifacts
on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-prestate-artifacts: 
    name: Publish Prestates Artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        kind: ["cannon"]
        version: ["kona", "kona-int"]
    steps: 
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false

      - uses: ./.github/actions/setup
        with:
          components: llvm-tools-preview
          prefix-key: ${{ matrix.kind }}

      - name: Authenticate to GCP
        id: 'auth'
        uses: google-github-actions/auth@v3
        with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/oplabs-tools-artifacts/locations/global/workloadIdentityPools/external-op-rs-ci/provider/github-op-rs-oidc'
          service_account: 'rust-enviroment-uploader@oplabs-tools-artifacts.iam.gserviceaccount.com'

      - uses: taiki-e/install-action@just

      - name: Generate prestate artifacts
        run: |
          HASH="$(cat .config/monorepo)"
          cd docker/fpvm-prestates
          just "${{ matrix.kind }}" "${{ matrix.version }}" "${{ github.ref_name }}" "$HASH"

      - name: Upload prestates artifacts to GCS
        run: |
             # Use the actual hash for tags (hash can be found by reading releases.json) 
             PRESTATE_HASH=$(jq -r .pre ./prestate-artifacts-${{ matrix.kind }}/prestate-proof.json) 
  
             BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-') 
             echo "Publishing ${PRESTATE_HASH} as ${BRANCH_NAME}" 
             if [[ "" != "${{ github.ref_name }}" ]] 
             then 
               echo "Publishing commit hash data" 
               INFO_FILE=$(mktemp) 

               # Upload the git commit info for each prestate since this won't be recorded in releases.json 
               (echo "Commit=${{ github.ref_name }}" && echo "Prestate: ${PRESTATE_HASH}") > "${INFO_FILE}" 

               gsutil cp "${INFO_FILE}" "gs://oplabs-network-data/proofs/op-program/kona/${{ matrix.kind }}/${BRANCH_NAME}-${{ matrix.version }}-prestate.bin.txt" 
               echo "Published commit hash data successfully" # So we know if any uploads worked 

               rm "${INFO_FILE}" # keep things tidy 
               echo "All commit info published" 
  
               # Use the branch name for branches to provide a consistent URL 
               PRESTATE_HASH="${BRANCH_NAME}-${{ matrix.version }}" 
             fi 

             gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"

             gsutil cp ./prestate-artifacts-${{ matrix.kind }}/prestate.bin.gz "gs://kona-proof-prestates/${{ matrix.kind }}/${PRESTATE_HASH}-prestate.bin.gz" 

             echo "Successfully published prestates artifacts to GCS"