name: Stale PR Management

on:
  schedule:
    # Run daily at 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    name: Close stale PRs
    steps:
      - name: Close stale PRs
        uses: actions/stale@v10
        with:
          # More Operations than default 30
          operations-per-run: 100

          # Issues should not be stale or closed
          days-before-issue-stale: -1
          days-before-issue-close: -1

          # Pull Request Stale
          days-before-pr-stale: 21
          days-before-pr-close: 7
          stale-pr-label: 'M-stale'
          exempt-pr-labels: 'M-prevent-stale'
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has been inactive for 3 weeks.
            It will be closed in 1 week if no further activity occurs.
            If you believe this PR should remain open, please add the `M-prevent-stale` label or leave a comment.
          close-pr-message: |
            This pull request has been automatically closed due to inactivity (4 weeks total).
            If you would like to continue working on this PR, please reopen it and ensure it stays active.
            You can also add the `M-prevent-stale` label to prevent automatic closure in the future.
            Thank you for your contributions.
