name: Sysgo E2E Tests Supervisor
on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  supervisor-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    name: ${{ matrix.test-pkg }}-tests
    strategy:
      fail-fast: false
      matrix:
        test-pkg: ["pre_interop", "l1reorg/sysgo"]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          submodules: true

      - uses: ./.github/actions/setup
        with:
          channel: stable

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false

      - uses: taiki-e/install-action@just

      - uses: jdx/mise-action@v3       # installs Mise + runs `mise install`

      - name: Setup Go 1.24.3
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.24.3'
          cache-dependency-path: "**/go.sum"

      - name: test ${{ matrix.test-pkg }}
        run: just test-e2e-sysgo supervisor "/supervisor/${{ matrix.test-pkg }}"
