name: Kurtosis Supervisor
on:
  workflow_dispatch:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  kurtosis-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    name: test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85
      - uses: jdx/mise-action@v2       # installs Mise + runs `mise install`
        with:
          cache: true                  # enable built‑in tool cache
      - name: run kurtosis superchain with kona-supervisor
        run: cd tests && just deploy simple-supervisor ${{ github.event.pull_request.head.sha }}
